name: it-tools
services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    image: corentinth/it-tools:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`ittools.localhost`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools-http.rule=Host(`ittools.localhost`)"
      - "traefik.http.routers.it-tools-http.entrypoints=web"
      - "traefik.http.routers.it-tools-http.middlewares=https-redirect@file"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    networks:
      - tools

networks:
  tools:
    external: true
